UrielOfir/os-practice

- docusaurus.config.js
Make the website Right-to-left
> change website Right-to-left

- docs/people/Menachem.md
How can I connect the PR with the issue?
> add Menachem to people

- docs/people/Roy Zerbib.md
I added a md file with my name. Please close issue #38 .
Thanks!
> - Adding a md file with my name

- docs/people/anukhe830.md
> add new md file with my name

- docs/people/Oshri.md
> i add a new md file

- docs/people/shlomi nugarker.md
> added my md file

- docs/people/Rivki Zohar.md
> Add my name

- docs/people/oren bochman.md
> new file:   docs/people/oren bochman.md

- LICENSE.md
- docs/people/oren bochman.md
> Open license

- docs/people/aharon karsenti.md
hey please add my commite to the site, its my first time doing it,
thanks
> Aharon joined

- docs/people/yarinkeren.md
> fix issue #68

- docs/people/eliram lugassi.md
add a new md file describing myself
closing issue #71
> add a new md. file from eliram lugassi

- docs/people/shmuel-cohen.md
> add my name again

- docs/people/Bella.md
contribute to this project by adding a new md file , adding a bella.md file
> adding bella.md

- docs/people/maor azriel.md
> added maor azriel.md

- docs/people/Binyamin Shapira.md
> added md file about myself

- docs/people/Ron Oren.md
> Added a md file about myself

- docs/people/Hila.md
> first commit

- docs/people/Ernest.md
Adding new Ernest.md file into people folder.
Want to close Issue: Adding md file #118
> Ernests branch

- docs/people/DrorPractice.md
> practicing os pull request - issue #137 

- docs/people/Tutorial.md
> os-tutorial

- imHungry.md
Im still hungry if anyone wondered
> Issue - add md file (named imHungry.md)

- package-lock.json
> Add MD file - rotem

- docs/people/Lampel.md
Please approve my lampel.md file
> added lampel.md file

- docs/people/Inbar.md
> adding new md file

- docs/people/Shai.md
> initial commit

- docs/people/shmuel.md
> added md file for practice

- docs/people/Alex.md
> Adding Alex.md file to the project

- docs/people/guy.md
> open source tutorial 

- docs/people/jerry_seinfeld.md
> Add jerry_seinfeld page

- docs/people/Bina.md
> os-practice-bina

- docs/people/Haiku.md
> my first commit

- docs/people/duck.md
Resolved #209 - added an MD file according to the tutorial instructions.
> add .md file

- docs/people/shaharzfrn.md
- package-lock.json
> shaharzfrn os-getting-started

- docs/people/ChagitA.md
- package-lock.json
> os tutorials

- docs/people/Simcha_card.md
adding my card 
Thanks for this cute practice site
> add a page

- docs/people/Tutorial.md
> Os tutorial

- docs/people/superk.md
Committer: @1superk1
Date: Wed Dec 20 14:27:39 IST 2023
On branch: guys-branch
New file: superk.md
> Guy's file is added to the forked repo

- docs/people/Bracha.md
> os-practice

- docs/people/yossi126.md
> os-tutorial-yossi126

- Trial.md
trying to upload .md file with image & txt
> tutorial trial

- docs/people/Moshe.md
> adding md file

- docs/people/Paz.md
> Add People file

- docs/people/Or Yehezkel.md
Added a new md file to practice open code
Resolving issue #289
> Added md file

- docs/people/Eden.md
> commit try

- docs/people/Futurama.md
add Futurama.md to:
docs/people
add text and image to the file
issue: #298
> Add New MD File

- docs/people/NeriaAtias.md
> os-NeriaAtias

- docs/people/Dor Mor.md
> adding my md file

- docs/people/David.md
> os-tutorial added my own page

- docs/people/pep.md
> add Pep page

- docs/people/Richard.md
#333 
added .md page in honor of Richard stallman.
included licensign for file used
> add .md page for Richard stallman

- docs/people/bart.md
adding bart.md file under people
> adding bart.md

- docs/people/Dora The Explorer.md
> [#343] resolve issue #343

- docs/people/shaked.md
> Added Shaked File

- docs/people/Ran Dom.md
adding Ran Dom to the list of people
> Yoni's contribution

- docs/people/Cat.md
> added an md file Practice

- docs/people/AgentT.md
os-tutorial add md file
Resolving #381
> add md file

- docs/people/NirBinjamin.md
> Nir BInjamin md file

- .github/workflows/check_people_md_pr.yml
using ascalgn/automerge-action@v0.16.3
[https://github.com/pascalgn/automerge-action?tab=readme-ov-file#configuration](url)
> automerge is active now

- docs/people/David Ohr.md
Hey i complited the practice resolving issue #399
> David Ohr file added

- docs/people/Tali.md
> Add Tali's md file

- docs/people/Aviv.md
> "added Aviv.md"

- docs/people/nimrod.md
> os-practice-nimrod

- docs/people/new joiner.md
> I added myself as a new member

- docs/people/Liad.md
> Add Liad Ovdat

- docs/people/Zappa.md
> os-tutorial Zappa

- docs/people/Yael.md
> os-tutorial - add new doc

- docs/people/mendi.md
i try  now the and success b"h to create a new file in true repo TU!
> my first try!

- docs/people/Niv.md
Hey,
Willing To Close PR #475 by Nivhaham,
Thanks,
Niv,
> Nivs branch

- docs/people/Niv.md
- docs/people/elishevaG.md
> add elishevaG.md to people

- docs/people/EFishman.md
Create a people names **E Fishman**
> E Fishman md

- docs/people/Talya.md
> Add new md

- docs/people/tuyorial_tamar.md
> os-tutorial-Tamar

- docs/people/gideonB.md
> File C added

- docs/people/Naama.md
> add md file 

- docs/people/st.md
> add-MD-file

- docs/people/Tamar_Co.md
> add md page

- docs/people/Shira.md
> addition my name

- docs/people/Rachel.md
> Racheli page.

- docs/people/RachelWeiner.md
> Rachel's MD

- docs/people/MichaelHoffman.md
Adding Michael Hoffman MD    
and practicing contirbutaion to open source.     
Resolving #600
> docs: add Michael Hoffman MD page

- docs/people/DanielTovbin.md
> os-practice-Daniel

- docs/people/Shoshana.md
> OS practice

- docs/people/AmberWeiner.md
> Add my md file.

- docs/people/AyeletD.md
> My first contribution - OS

- docs/people/sivan.md
Hey Uriel,
added an MD file.
Sivan
> Sivan add md file

- docs/people/MiriKa.md
> OS-firs time

- docs/people/Stav.md
> OS - toturial

- docs/people/RuthB.md
> RuthB , add my md file

- docs/people/zevi.md
> os-totorial

- docs/people/Evyatar.md
- package-lock.json
> os-tutorial-evyatar

- docs/people/Meir Crombie.md
> Add personal README for Meir Crombie with GitHub stats and contact links

- docs/people/ElishevaC.md
> os-elishevaC

- docs/people/Arye.md
> add md Arye

- docs/people/Talia.md
> os-tutorial-talia

- docs/people/IlayRomi.md
> Ilays practice
